# Practice Exercises

*Appying `numpy` to Conway's Game of Life.*

We first introduced a model of the Game of Life as a way to introduce classes (objects). In this notebook we will instead use `numpy` to model the grid where our 'cells' live. Since it turns out that these cells do not require any more information that alive (1), or dead (0).

## *Task -- Setup*

**Import `numpy` as `np`.**

In [1]:
# Setup imports.
import numpy as np

# Questions




```python
who_array = np.array([[[2,3,4,5], [1,2,3,4]], [[5,6,7,8], [1,2,3,4]]])

print(who_array)

you_array = np.append(who_array, [[[7], [8]], [[9], [1]]], axis=2)

print("\n")

print(you_array)

me_array = np.append(you_array, [[[7], [4], [5], [4]]], axis=1)

print("\n")

print(me_array)
```

In [2]:
who_array = np.array([[[2,3,4,5], [1,2,3,4]], [[5,6,7,8], [1,2,3,4]]])
who_array

array([[[2, 3, 4, 5],
        [1, 2, 3, 4]],

       [[5, 6, 7, 8],
        [1, 2, 3, 4]]])

In [3]:
who_array.shape  # Dimsions 2, 0, 1

(2, 2, 4)

In [4]:
np.append(who_array, [[[7], [8]], [[9], [1]]], axis=2)

array([[[2, 3, 4, 5, 7],
        [1, 2, 3, 4, 8]],

       [[5, 6, 7, 8, 9],
        [1, 2, 3, 4, 1]]])

In [5]:
np.append(who_array, np.array([7, 8, 9, 1]))

array([2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 7, 8, 9, 1])

*Dimension Detail*

In [6]:
new_array = np.array([7, 8, 9, 1])
new_array

array([7, 8, 9, 1])

In [7]:
new_array.shape

(4,)

We are trying to add to what dimension?

In [8]:
who_array[:, :, :]  # Get an entire copy, one slice per dimension.

array([[[2, 3, 4, 5],
        [1, 2, 3, 4]],

       [[5, 6, 7, 8],
        [1, 2, 3, 4]]])

In [9]:
who_array[...]  # Another way.

array([[[2, 3, 4, 5],
        [1, 2, 3, 4]],

       [[5, 6, 7, 8],
        [1, 2, 3, 4]]])

In [10]:
who_array[:, :, -1]  # Slice the last element from each dimension.

array([[5, 4],
       [8, 4]])

In [11]:
who_array[:, -1, :]

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [12]:
who_array[-1, :, :]

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

We want to add on to dimension `1`. What is the dimension of the slice we retrived?

In [13]:
who_array[:, :, -1].shape

(2, 2)

In [14]:
new_array.reshape(2, 2, 1)

array([[[7],
        [8]],

       [[9],
        [1]]])

In [15]:
np.append(who_array, new_array.reshape(2, 2, 1), axis=2)

array([[[2, 3, 4, 5, 7],
        [1, 2, 3, 4, 8]],

       [[5, 6, 7, 8, 9],
        [1, 2, 3, 4, 1]]])

Or, in the documentation, under **Array manipulation routines**:

>...  
`dstack(tup)` 	Stack arrays in sequence depth wise (along third axis).  
`hstack(tup)`	Stack arrays in sequence horizontally (column wise).  
`vstack(tup)` 	Stack arrays in sequence vertically (row wise).  
...

In [16]:
np.dstack([who_array, new_array.reshape(2,2)])

array([[[2, 3, 4, 5, 7],
        [1, 2, 3, 4, 8]],

       [[5, 6, 7, 8, 9],
        [1, 2, 3, 4, 1]]])

## Game of Life Overview


The rules, as summarized by [Wolfram Alpha](http://mathworld.wolfram.com/GameofLife.html).

> All eight of the cells surrounding the current one are checked to see if they are on or not. Any cells that are on are counted, and this count is then used to determine what will happen to the current cell.
1. **Death**: if the count is less than 2 or greater than 3, the current cell is switched off.
2. **Survival**: if (a) the count is exactly 2, or (b) the count is exactly 3 and the current cell is on, the current cell is left unchanged.
3. **Birth**: if the current cell is off and the count is exactly 3, the current cell is switched on. 

It turns out that some people are *really* into this game. There are a large number of solutions available online, we will look at a few, and consider our own.


#### Solutions Examined

+ [Peter Norvig](https://nbviewer.jupyter.org/url/norvig.com/ipython/Life.ipynb) -- *Does not model a grid, instead keeps track of a set of cells (as coordinate tuples), then draws a grid. Entire thing runs in a jupyter notebook. Writes great (and fast) code, but has a tendancy to rename (alias) builtins.*
+ [Holoviews Solution](http://holoviews.org/gallery/apps/bokeh/game_of_life.html#bokeh-gallery-game-of-life) -- *This implementation is exceptionally brief, as it is able to use some features from the `Holoviews` package, for drawing and 'ticking' the world.*


*General Information:*  
+ [See How seriously people are in to this.](http://www.conwaylife.com/)
+ [Wikipidia Ariticle](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life)

![Breader pattern](https://upload.wikimedia.org/wikipedia/commons/e/e6/Conways_game_of_life_breeder_animation.gif)

---

## Keep it Simple

*Walk through of a simple solution.*

Get it working first. Then try to make it better.

### Building a Grid

Recall that there are 'array constructor' functions in numpy that are nice for building up arrays.

In [17]:
# A 10 by 10 grid of dead cells.
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

*Perhaps we want a randomly populated grid.*

```python
np.randint(low[, high, size, dtype])
```

In [18]:
np.random.randint(0, 2, (10, 10), np.int)

array([[0, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [1, 1, 0, 1, 1, 0, 0, 0, 0, 1],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 1],
       [0, 1, 1, 1, 1, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 0, 1, 1, 0, 0, 1],
       [0, 0, 1, 1, 1, 1, 1, 0, 0, 1],
       [1, 1, 1, 0, 0, 0, 0, 1, 1, 1],
       [1, 0, 0, 1, 0, 1, 1, 1, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

*These are all well and good, but if you want unique numbers to help wrap your head around indexing...*

In [19]:
unique_grid = np.arange(0, 100).reshape((10, 10))
unique_grid

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Determining Fates

*We will now impose time and our cruel will upon these innocent worlds.*

How can we calculate if a cell should live or die?

In [20]:
# Recall some indexing, start with getting just one cell.
grid = np.random.randint(0, 2, (10, 10), np.int)

In [21]:
# These two calls are equivalent.
assert all(unique_grid[0] == unique_grid[0, :])

# Choose to be explicit when learning.
unique_grid[0, :]  # A horizontal slize.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
unique_grid[:, 0]  # A vertical slice.

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Slices can be passed too.

In [23]:
unique_grid[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [24]:
unique_grid[5:8, 5:8]

array([[55, 56, 57],
       [65, 66, 67],
       [75, 76, 77]])

### Looping of the Array

If you want to loop over something in Python, don't bother with indexes unless you have a specific order you need to go through. Simply call the object in a loop.

*This usually access the __iter__() function of a given object.*

In [25]:
for row in unique_grid:
    print(row)
    for item in row:
        print(item)
    break  # Stop this loop.

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


**I want my loop and I want my numbers together or I am taking my ball and going home.**

In [26]:
for row_index, row in enumerate(unique_grid):
    for col_index, cell in enumerate(row):
        print(row_index, col_index)
    break

0 0
0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9


### Getting the Neighbors

*And your little dog, too.*

With the grid, indexing and looping in their first forms, we are ready to start composing functions. Let's write a function that loops over a given grid, and prints the coordinates of its 8 neighbors.

*We can make an easy start by using some code from above:*

In [27]:
def display_neighbor_coords(input_grid):
    print("Showing current loop position...")
    for row_index, row in enumerate(input_grid):
        for col_index, cell in enumerate(row):
            print(row_index, col_index)

Test it with a smaller grid to avoid printing 100+ lines.

In [28]:
test_grid = np.random.randint(0, 2, (3, 3), np.int)
test_grid

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [29]:
display_neighbor_coords(test_grid)

Showing current loop position...
0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


Actually getting the neighbors is separate from the loop. Come to think of it... If we want to know the coordinates of anyones neighbors, we need only know their coordinates.

In [30]:
def get_neighbor_indexes(x, y):
    """Return a set of indexes of the 8 neighbors to x, y."""
    return  [(x - 1, y + 1), (x, y + 1), (x + 1, y + 1),
             (x - 1, y    ),             (x + 1, y    ),  # My actual 'center' (x, y) is in the hole here.
             (x - 1, y - 1), (x, y - 1), (x + 1, y - 1)]

Why tuples?

In [31]:
get_neighbor_indexes(0, 0)

[(-1, 1), (0, 1), (1, 1), (-1, 0), (1, 0), (-1, -1), (0, -1), (1, -1)]

In [32]:
get_neighbor_indexes(5, 5)

[(4, 6), (5, 6), (6, 6), (4, 5), (6, 5), (4, 4), (5, 4), (6, 4)]

Another approach would be to slice around the x, y location.

In [33]:
def get_neighbor_coors(grid, x, y):
    return grid[x - 1 : x + 2, 
                y - 1 : y + 2]

In [34]:
get_neighbor_coors(unique_grid, 2, 2)

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [35]:
get_neighbor_coors(unique_grid, 5,7)  # Let's not concern ourselves with edge cases for now.

array([[46, 47, 48],
       [56, 57, 58],
       [66, 67, 68]])

In this case we could apply another 'mask' of booleans to remove thie center point.

In [36]:
bool_idx = np.array([[True, True, True], [True, False, True], [True, True, True]])
bool_idx

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [37]:
get_neighbor_coors(unique_grid, 2, 2)[bool_idx]

array([11, 12, 13, 21, 23, 31, 32, 33])

## Consider the Life and Death Conditions

First lets finalize an application of our neighbor fetching to a grid of 0 and 1.

In [38]:
grid = np.random.randint(0, 2, (10, 10), np.int)
grid

array([[0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 1, 0, 0, 0, 1, 0, 1]])

In [39]:
def neighbors_1(grid, x, y):
    return [grid[coords] for coords in get_neighbor_indexes(x, y)]

In [40]:
neighbors_1(unique_grid, 2, 2)

[13, 23, 33, 12, 32, 11, 21, 31]

In [41]:
neighbors_1(grid, 2, 2)

[1, 0, 1, 1, 0, 1, 0, 0]

In [42]:
def neighbors_2(grid, x, y):
    bool_idx = np.array([[True, True, True], [True, False, True], [True, True, True]])
    return get_neighbor_coors(grid, x, y)[bool_idx]

In [43]:
neighbors_2(unique_grid, 2, 2)

array([11, 12, 13, 21, 23, 31, 32, 33])

In [44]:
neighbors_2(grid, 2, 2)

array([1, 1, 1, 0, 0, 0, 0, 1])

## Calculating Life and Death

> All eight of the cells surrounding the current one are checked to see if they are on or not. Any cells that are on are counted, and this count is then used to determine what will happen to the current cell.
1. **Death**: if the count is less than 2 or greater than 3, the current cell is switched off.
2. **Survival**: if (a) the count is exactly 2, or (b) the count is exactly 3 and the current cell is on, the current cell is left unchanged.
3. **Birth**: if the current cell is off and the count is exactly 3, the current cell is switched on. 

In [45]:
def determine_fate(grid, x, y):
    
    neighbors = neighbors_2(grid, x, y)
    
    xy_state = grid[(x, y)]

    print(f"Center cell state: {xy_state}")
    
    alive_neighbors = np.sum(neighbors)
    print(f"Alive neighbors: {alive_neighbors}")
    
    if xy_state == 0 and alive_neighbors == 3:
        print('Birth!')
        return 1
    
    if xy_state == 1 and (alive_neighbors == 2 or alive_neighbors == 3):
        print('Staying alive.')
        return 1
    
    if xy_state == 1 and (alive_neighbors < 2 or alive_neighbors > 3):
        print('Another one bites the dust.')
        return 0

    return None  # This is not needed, it is implicit.

In [46]:
determine_fate(grid, 3, 3)

Center cell state: 1
Alive neighbors: 1
Another one bites the dust.


0

If only we could test it...

In [47]:
# Nothing should happen here.
test_1 = np.array([
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
])

# This cell should perish.
test_2 = np.array([
    [0, 0, 0],
    [0, 1, 0],
    [0, 0, 0]
])

# This cell should be born.
test_3 = np.array([
    [0, 1, 0],
    [0, 0, 1],
    [0, 1, 0]
])


# This cell should live.
test_4 = np.array([
    [0, 0, 0],
    [0, 1, 0],
    [0, 1, 1]
])

`(1, 1)` should be the center, and the desired 'test cell'.

In [48]:
determine_fate(test_1, 1, 1)

Center cell state: 0
Alive neighbors: 0


In [49]:
determine_fate(test_2, 1, 1)

Center cell state: 1
Alive neighbors: 0
Another one bites the dust.


0

In [50]:
determine_fate(test_3, 1, 1)

Center cell state: 0
Alive neighbors: 3
Birth!


1

In [51]:
determine_fate(test_4, 1, 1)

Center cell state: 1
Alive neighbors: 2
Staying alive.


1

# Time

In [52]:
import time

In [53]:
def run_world(grid, ticks=1000):
    
    for t in np.arange(ticks):
        
        # Calculate the fate of the cells.
        
        
        # Update (or replace) the grid.
        
        
        # Display the new grid.
        print(grid)
        
        # Wait for the humans to grow comnplacent.
        time.sleep(0.05)  # 1/20 seconds.

In [54]:
run_world(grid)

[[0 1 0 0 0 0 1 0 0 0]
 [1 1 1 1 1 0 1 1 1 0]
 [1 0 0 0 0 1 0 0 0 0]
 [1 0 0 1 0 1 0 1 0 1]
 [0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 1 1 1 1 1 0]
 [0 1 1 0 0 0 0 0 0 1]
 [1 1 1 1 1 0 0 1 0 1]
 [1 0 1 0 1 1 1 1 0 1]
 [1 0 0 1 0 0 0 1 0 1]]
[[0 1 0 0 0 0 1 0 0 0]
 [1 1 1 1 1 0 1 1 1 0]
 [1 0 0 0 0 1 0 0 0 0]
 [1 0 0 1 0 1 0 1 0 1]
 [0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 1 1 1 1 1 0]
 [0 1 1 0 0 0 0 0 0 1]
 [1 1 1 1 1 0 0 1 0 1]
 [1 0 1 0 1 1 1 1 0 1]
 [1 0 0 1 0 0 0 1 0 1]]
[[0 1 0 0 0 0 1 0 0 0]
 [1 1 1 1 1 0 1 1 1 0]
 [1 0 0 0 0 1 0 0 0 0]
 [1 0 0 1 0 1 0 1 0 1]
 [0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 1 1 1 1 1 0]
 [0 1 1 0 0 0 0 0 0 1]
 [1 1 1 1 1 0 0 1 0 1]
 [1 0 1 0 1 1 1 1 0 1]
 [1 0 0 1 0 0 0 1 0 1]]
[[0 1 0 0 0 0 1 0 0 0]
 [1 1 1 1 1 0 1 1 1 0]
 [1 0 0 0 0 1 0 0 0 0]
 [1 0 0 1 0 1 0 1 0 1]
 [0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 1 1 1 1 1 0]
 [0 1 1 0 0 0 0 0 0 1]
 [1 1 1 1 1 0 0 1 0 1]
 [1 0 1 0 1 1 1 1 0 1]
 [1 0 0 1 0 0 0 1 0 1]]
[[0 1 0 0 0 0 1 0 0 0]
 [1 1 1 1 1 0 1 1 1 0]
 [1 0 0 0 0 1 0 0 0 0]
 [1 0 0

Plan your functions!

---

# Holoviews Solution

Examine what is happening here.

```python
def step(X):
    nbrs_count = convolve2d(X, np.ones((3, 3)), mode='same', boundary='wrap') - X
    return (nbrs_count == 3) | (X & (nbrs_count == 2))
```

The `convolve2d()` function is from the `scipy.signal` package. While we wont cover this function (or most of `scipy` in this class, a quick dive into another package can make a good lesson. See if you can figure out what the function above does with the help of the code below.

In [55]:
from scipy.signal import convolve2d

In [56]:
def test_convolve2d(in1, in2, mode='full', boundary='fill', fillvalue=0):
    # The defualt arguments for the function are filled above.
    print('Input array:')
    print(in1)
    out = convolve2d(in1, in2, mode, boundary, fillvalue)
    print('Output:')
    print(out)

In [57]:
test_convolve2d(test_1, np.ones((3, 3)), mode='same')

Input array:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Output:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [58]:
test_convolve2d(test_2, np.ones((3, 3)), mode='same')

Input array:
[[0 0 0]
 [0 1 0]
 [0 0 0]]
Output:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [59]:
test_convolve2d(test_3, np.ones((3, 3)), mode='same')

Input array:
[[0 1 0]
 [0 0 1]
 [0 1 0]]
Output:
[[1. 2. 2.]
 [2. 3. 3.]
 [1. 2. 2.]]


In [60]:
test_convolve2d(test_4, np.ones((3, 3)), mode='same')

Input array:
[[0 0 0]
 [0 1 0]
 [0 1 1]]
Output:
[[1. 1. 1.]
 [2. 3. 3.]
 [2. 3. 3.]]


In [61]:
test_convolve2d(grid, np.ones((3, 3)), mode='same')

Input array:
[[0 0 1 0 1 1 1 1 0 1]
 [0 1 0 0 1 0 0 0 0 1]
 [1 0 0 1 0 1 0 1 0 1]
 [0 0 1 1 1 0 1 1 1 0]
 [0 0 1 0 1 0 1 1 0 1]
 [0 0 1 0 1 1 0 0 1 0]
 [0 1 0 0 0 0 1 1 1 0]
 [1 1 1 1 0 1 0 1 1 1]
 [0 1 1 1 0 1 1 1 1 1]
 [0 1 1 0 0 1 1 1 0 0]]
Output:
[[1. 2. 2. 3. 3. 4. 3. 2. 3. 2.]
 [2. 3. 3. 4. 5. 5. 5. 3. 5. 3.]
 [2. 3. 4. 5. 5. 4. 4. 4. 5. 3.]
 [1. 3. 4. 6. 5. 5. 6. 6. 6. 3.]
 [0. 3. 4. 7. 5. 6. 5. 6. 5. 3.]
 [1. 3. 3. 4. 3. 5. 5. 6. 5. 3.]
 [3. 5. 5. 4. 4. 4. 5. 6. 6. 4.]
 [4. 6. 7. 4. 4. 4. 7. 8. 8. 5.]
 [4. 7. 8. 5. 5. 5. 8. 7. 7. 4.]
 [2. 4. 5. 3. 3. 4. 6. 5. 4. 2.]]


In [62]:
nbrs_count = convolve2d(grid, np.ones((3, 3)), mode='same') - grid
nbrs_count

array([[1., 2., 1., 3., 2., 3., 2., 1., 3., 1.],
       [2., 2., 3., 4., 4., 5., 5., 3., 5., 2.],
       [1., 3., 4., 4., 5., 3., 4., 3., 5., 2.],
       [1., 3., 3., 5., 4., 5., 5., 5., 5., 3.],
       [0., 3., 3., 7., 4., 6., 4., 5., 5., 2.],
       [1., 3., 2., 4., 2., 4., 5., 6., 4., 3.],
       [3., 4., 5., 4., 4., 4., 4., 5., 5., 4.],
       [3., 5., 6., 3., 4., 3., 7., 7., 7., 4.],
       [4., 6., 7., 4., 5., 4., 7., 6., 6., 3.],
       [2., 3., 4., 3., 3., 3., 5., 4., 4., 2.]])

In [63]:
(nbrs_count == 3) | (grid & (nbrs_count == 2))

array([[0, 0, 0, 1, 1, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 1, 1, 0, 0, 0, 0]], dtype=int32)

See `np.bitwise_and` and `np.bitwise_or`.
